main:
  - name: Home
    url: /
    weight: 10
  - name: News
    url: /#news
    weight: 20
    # - name: Projects
    #   url: '#projects'
    #   weight: 30
  - name: Résumé
    url: /uploads/resume.pdf
    weight: 40
  - name: Contact
    url: 'mailto:contact@hazemhussien.xyz'
    weight: 50
